---
title: How do I search for SQL help?
author: James Gill
date: '2020-09-14'
slug: finding-sql-docs
categories:
  - SQL
tags:
  - SQL
  - T-SQL
  - SQL Server
  - Early career
description: ''
thumbnail: ''
---

Like most people, I'm quick to turn to Google when I need to know something, and Google searches for SQL-related questions throw up plenty of results from sites like [StackOverflow](https://stackoverflow.com/questions/tagged/sql?tab=Frequent).

However, many companies produce database software, and many of these products are queried using a language called "SQL". But it turns out that each product has its own dialect. Keywords that work in one product may not work in another - and so the answer you find may not work in your database.

One way to improve your results is to include the name of the dialect of SQL that you need to use in your search. I work with Microsoft SQL Server, which uses a SQL dialect called T-SQL, and so I use search terms like "CREATE TABLE **TSQL**" rather than "CREATE TABLE **SQL**".

I also tend to start by looking at the official documentation website for the dialect of SQL I'm using, particularly if I just want to clarify a point of syntax. For SQL Server, that's [Microsoft Docs](https://docs.microsoft.com/en-us/sql/t-sql/queries/queries).